version: 0.2 # Specifies the version of the Buildspec file format.

phases:
  install:
    commands:
      - echo "Installing dependencies..........."
      - echo "Node version.....:$(node -v)"
      - echo "NPM version......:$(npm -v)"
      - npm install # Placeholder for installing dependencies.
  pre_build:
    commands:
      - echo "Running unit tests..........."
      - npm run test
  build:
    commands:
      - echo "Building the App..........."
artifacts:
  files:
    # - "build/**/*"
    - "**/*" # Specifies all files in the 'build' directory to be included as artifacts.
  base-directory: build # Specifies the base directory for the artifacts.
