version: 0.2 # Specifies the version of the Buildspec file format.

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..........." # Placeholder for any installation commands (none needed here).
      - npm install
  build:
    commands:
      - echo "Building the Preact App..........." # Placeholder for build commands.
      - npm run build
artifacts:
  files:
    - "build/**/*"
    # - "**/*" # Specifies all files in the 'build' directory to be included as artifacts.
  base-directory: build # Specifies the base directory for the artifacts.
